### ISSUE TITLE
Determine site hierarchy 

### ISSUE THREAD

**Issue by cgreim** [CornerFarmChicago/farm-site#1]
We went through the old site hierarchy and made a first pass at a new one.

[Site Hierarchy Notes](https://docs.google.com/document/d/1joLol8wxypVrDITgmVo9WQWDOn4Tu_l2j3jy7_GjaZQ/edit)

Cat needs to share this with farm folks and get sign off / make edits if needed.

**Comment by cgreim** [comment]
Proposed site map is in a new doc: [Site Map](https://docs.google.com/document/d/1n_UvK8jDrzBQP1Fyv_e6YE3wASdNtzc384-LhmRyaN8/edit#)

## about
- mission & vision
- altgeld sawyer 

## get involved
- volunteering 
- compost 
- public events 
- partnerships 

## resources 
- CFC volunteers
- general farming

## calendar
- google calendar

**Comment by sambors** [comment]
I've been thinking about navigation as we're working on the "About" section (Mission/Vision and Altgeld Sawyer). I think it might be a good idea to flatten these pages into a single "About" page, I think it would make the navigation simpler and those particular sections are likely short enough that I don't think we need separate pages. I'm willing to bet that someone coming to the website to learn about us would like to learn about our mission and about the farm itself, and having everything on one page would make this easier (instead of needing to go back up to the navbar and click again on another section).

That said, I'll continue to work independently on the Altgeld/Sawyer page, we can always merge the pages later or keep them separate.

**Comment by cgreim** [comment]
Suggestion to add a Donate page, to keep a running list of things the farm needs and eventually be a place where we could ask for $$ 

Probably makes sense to put this under Get Involved 

## get involved
- volunteering 
- donate
- compost 
- public events 
- partnerships

**Comment by cgreim** [comment]
We're in a good place with site map! Expecting some edits depending on what we're reading to launch with but we're on the same page about what goes where. Closing this.
